### ISSUE TITLE
Extremely Minor Request: "Normal" NPM Package

### ISSUE THREAD

**Issue by machineghost** [3846masa/axios-cookiejar-support#100]
Fist off thanks so much for adding cookie support to Axios.  However, I have one *very* minor request: a "normal" package name.

I know that:

    "@3846masa/axios-cookiejar-support": "^0.1.1",

is a perfectly legit NPM package ... but when you see it in a long list of package names that have neither "`@`" nor "`/`" it look like you're using some strange amateur-written code in the middle of your otherwise professional dependency list.

Any chance you could "normalize" axios cookie jar support's NPM package name?  If not it's (obviously) not important, but I figured it couldn't hurt to ask.

**Comment by 3846masa** [comment]
Sorry for late response.
I'll also release normalized package name since v0.1.3.

See https://www.npmjs.com/package/axios-cookiejar-support
