### ISSUE TITLE
Error: Cannot find module 'axios-cookiejar-support'

### ISSUE THREAD

**Issue by oott123** [3846masa/axios-cookiejar-support#118]
When I use `npm i axios axios-cookiejar-support` to install and use this package, it throws `axios-cookiejar-support` when I trying to `require('axios-cookiejar-support');` under node v8.1.2.

I looked into the `node_modules/axios-cookiejar-support` and find that none of your files has been compiled and they leaved as `.mjs` files. Meanwhile, package.json says that the main file of this module is `./lib/index`.

When we require modules using `require` funtions, it can not require esm modules even in the latest nodejs. I can only use `import` synatx and with the very new nodejs if I want to use your package but this never mentioned in anywhere of your docs.

I found that you have babel and build scripts in your repo. So here is the question: why you keep compiled `.js` files out of the npm publish? (They are ignored by `.gitignore`, which will be used as `.npmignore` if there is not one.)

**Comment by 3846masa** [comment]
Sorry for users.
I'll republish.

**Comment by 3846masa** [comment]
Fixed and released as v2.0.1.
@oott123 , Thanks for your report!
