### ISSUE TITLE
Redirections are followed on non-redirect status codes

### ISSUE THREAD

**Issue by Yantrio** [3846masa/axios-cookiejar-support#133]
https://github.com/3846masa/axios-cookiejar-support/blob/a1f2c24cd17e1865890b76024b494ae4add64183/lib/interceptors/response.mjs#L33

This code here seems to ignore the statuscode returned, and will follow a redirect.
This becomes an issue when a Location header is set on a 201 Created response and the user may not want to follow that redirect.

For now I think I can work around this by setting {maxRedirects : 0} in the config per request, but its not a very nice solution.

**Comment by 3846masa** [comment]
Thanks for reporting 👍 
I'll fix it in a few days.

**Comment by 3846masa** [comment]
Fixed and released as v0.3.3.

**Comment by philjones88** [comment]
Still broken.

Updated to 0.3.4 and removed our workaround of `{ maxRedirects: 0} `. It broke our application.

Did a git revert to 0.3.2 and the workaround, it works again.

**Comment by 3846masa** [comment]
@philjones88 Thanks for reporting.
Please send sample code which caused this issue via gist.
