### ISSUE TITLE
Can't use with react-native?

### ISSUE THREAD

**Issue by kernel-sanders** [3846masa/axios-cookiejar-support#143]
I'm trying to add cookiejar support to axios in react-native. After installing with
`npm install --save axios-cookiejar-support` the react-native bundler breaks with the following error:

```
error: bundling failed: ReferenceError: Unknown plugin "module:@babel/plugin-transform-modules-commonjs" specified in "/Users/.../[project]/node_modules/axios-cookiejar-support/.babelrc" at 0, attempted to resolve relative to "/Users/.../[project]/node_modules/axios-cookiejar-support"
```

I can see that the axios-cookiejar-support .bablerc file does contain that plugin, and its listed under devDependencies in the package.json. Running `npm install --save @babel/plugin-transform-modules-commonjs` in the `[project]/node_modules/axios-cookiejar-support` directory has to effect. Any idea how to resolve this?

**Comment by 3846masa** [comment]
babel-plugins are devDependencies, there aren't necessary to install.
Please check your build config (webpack.config.js or .babelrc).

NOTE: I don't know this library can use with react-native, but maybe can't I think.

**Comment by kernel-sanders** [comment]
I ended up not using this package. Adding `withCredentials: true` to a standard Axios request seems to save cookies and send them with subsequent requests.
