### ISSUE TITLE
axiosCookieJarSupport is not a function

### ISSUE THREAD

**Issue by devmsg** [3846masa/axios-cookiejar-support#148]
hello 
axios version: 0.18.0
"axios-cookiejar-support": "^0.3.5"

axiosCookieJarSupport is not a function

**Comment by 3846masa** [comment]
Hi.
Please write more details for solving (os, node version, your code etc.).

**Comment by devmsg** [comment]
node: 9.10.1

![Uploading 24969287-1CD0-428E-82F4-7DDAE3782EF5.png…]()

**Comment by 3846masa** [comment]
Closed.
If you have issues yet, please resend issues with details.
