### ISSUE TITLE
Redirects not followed and 3xx responses are thrown as errors

### ISSUE THREAD

**Issue by evyatarmeged** [3846masa/axios-cookiejar-support#161]
Hey Masahiro,

It seems that all redirects are returned as errors. This is not the default behavior for `axios`.
It is, however, possible to bypass this by adding the following after calling `axiosCookieJarSupport(axios)`:<br>
```
axios.defaults.validateStatus = function(status) {
	return status >= 200 && status < 400
}
```

However, no matter how I tried editing the `maxRedirects` option (global config/individual request settings) it never seems to follow redirects thus leaving me stuck with 301 response data :<>

Just a heads up to you. I'll try to have a PR with a solution in the next few days.

**Comment by evyatarmeged** [comment]
Also, if it helps, package versions:

- axios-cookiejar-support: 0.4.2
- axios: 0.18.0
- tough-cookie: 2.4.3
- Node version: 10.11.0

**Comment by srquinn21** [comment]
validateStatus doesn't work with this plugin as it deletes it:
https://github.com/3846masa/axios-cookiejar-support/blob/master/lib/interceptors/request.mjs#L33
