### ISSUE TITLE
The plugin removes the validateStatus feature of the main client

### ISSUE THREAD

**Issue by srquinn21** [3846masa/axios-cookiejar-support#168]
I'm sure you have good reasons to do this:
https://github.com/3846masa/axios-cookiejar-support/blob/master/lib/interceptors/request.mjs#L33

But why is it not restored? As a result, consumers of this plugin get only a subset of the axios functionality. Worse yet, we spend hours debugging to find out it doesn't work because of a 3p integration.

**Comment by 3846masa** [comment]
I agree with your opinion, I'll fix this in a few days.

**Comment by 3846masa** [comment]
I check my code, `validateStatus` will be restored.
https://github.com/3846masa/axios-cookiejar-support/blob/09e98c36c35f48399cfa777dde75158cbbe74746/lib/interceptors/response.mjs#L48-L50
