### ISSUE TITLE
The plugin will cause a Maximum Call Stack Exceeded error when using an https.Agent

### ISSUE THREAD

**Issue by srquinn21** [3846masa/axios-cookiejar-support#169]
When adding an https.Agent to the config and then including this library, the process will hit the maximum allowed callstack of the nodejs process. This is because of the redirect behavior in the request interceptor.

The only way to get around this bug is to only include the https.Agent in the request level config and not the global or instance configs. This is super annoying if you want to provide your client as a library since your consumer would then need to add the https.Agent to each of their requests. Ugh.

**Comment by 3846masa** [comment]
Thanks for reporting.
So, for understanding this issue, please share a sample code via git?

**Comment by 3846masa** [comment]
I'll close this issue because of no longer response.
When you have not resolved yet, please reopen.

**Comment by srquinn21** [comment]
Sorry — I don't check here enough and missed your response. I'll put together a gist to demonstrate in the next few days and reopen when available. Thanks!

**Comment by denizaydemir** [comment]
Still has this issue
