### ISSUE TITLE
Bug (Maybe) cookies are duplicated on subsequent redirects

### ISSUE THREAD

**Issue by moltar** [3846masa/axios-cookiejar-support#228]
I am not sure if this is a bug yet, trying to reproduce and write some tests, but cannot due to #227 

But figured I'll open an issue, just in case, maybe you can spot the error, if there is one.

Here is a sanitized request flow:

```
GET /url1 HTTP/1.1
Cookie: cookiename=111111;
Host: example.com


HTTP/1.1 302 Found
Location: https://example.com/url2


GET /url2 HTTP/1.1
Cookie: cookiename=111111; cookiename=111111;
Host: example.com


HTTP/1.1 302 Found
Location: /url3
Set-Cookie: cookiename=222222; Domain=example.com; Expires=Thu, 10-Nov-2039 23:46:26 GMT; Path=/


GET /url3 HTTP/1.1
Cookie: cookiename=111111; cookiename=111111; cookiename=222222;
Host: example.com
```

Notice that with each request the cookies get appended and they have duplicate names.

**Comment by 3846masa** [comment]
Thanks for reporting.

It seems to be a bug.
I'll fix it.

**Comment by 3846masa** [comment]
It was fixed for v0.5.1.
Please try it.

**Comment by moltar** [comment]
Thanks for fixing it so fast!

**Comment by dheerajaggarwal** [comment]
I am still facing this issue with v0.5.1.

**Comment by 3846masa** [comment]
Please share the sample code caused this issue.

**Comment by dheerajaggarwal** [comment]
Thanks for the quick response. Let me write a test (sample code) for this.

**Comment by dheerajaggarwal** [comment]
Hi, sorry about the trouble. By mistake I was sending the cookie header by using the axios headers option. Your plugin also adds the same cookie from the cookie jar. That is why it was duplicated.

You may close this issue.
