### ISSUE TITLE
cookies not showing in browser

### ISSUE THREAD

**Issue by bghimire2** [3846masa/axios-cookiejar-support#247]
I followed the examples provided in the git repo, and it works fine in nodejs. When I print out the cookies using console.log(cookieJar.toJSON()) in nodejs it shows the cookies

But when I run this in the browser using reactjs/nextjs, after the api call, printing output using console.log(cookieJar.toJSON()) does not show any cookies. Also in the browser when I print using console.log(axiosCookieJarSupport), I see:

function noopEnableCookieJarSupport (instance) {
  return instance;
}

Is there a reason this does not work in the browser? Is there a way to make this work in the brrowser?

**Comment by 3846masa** [comment]
JavaScript in browser cannot get cookies via response.
Please use `document.cookies`.
This library is for server-side Node.js.

**Comment by bghimire2** [comment]
thanks for your help
