### ISSUE TITLE
Secured cookie not sent

### ISSUE THREAD

**Issue by razafinarivohanania** [3846masa/axios-cookiejar-support#276]
Hello, i use version `0.5.1`of `axios-cookiejar-support`. I connect on page A. It answers cookie like this :

`sessionId=xxxx; Path=/; Secure`

Then, i need this sessionId allowing me to connect another page B but it is never sent. After checking my raw request headers, Cookie is absent. By default, tough-cookie does not provide secured cookie.

```js
const tough = require('tough-cookie');
const Cookie = tough.Cookie;

const securedCookie = Cookie.parse('sessionId=xxxx; Path=/; Secure');
const simpleCookie = Cookie.parse('key=value; Path=/');

const url = 'http://www.example.com/';
const cookieJar = new tough.CookieJar();

cookieJar.setCookie(securedCookie, url, () => { });
cookieJar.setCookie(simpleCookie, url, () => { });

cookieJar.getCookies(url, (err, cookies) => {
    //Output : key=value
    console.log(cookies.map(cookie => cookie.cookieString()).join('; '));
});

cookieJar.getCookies(url, { secure: true }, (err, cookies) => {
    //Output : sessionId=xxxx; key=value
    console.log(cookies.map(cookie => cookie.cookieString()).join('; '));
});
```

So, i think an option which authorizes secured cookie is to add. Thanks in advance :)

**Comment by 3846masa** [comment]
Generally, cookies with the `Secure` directive are sent only over HTTPS.
Even with tough-cookie, a cookie with the `Secure` directive is returned only when the URL starts with ` https: `.
So this behavior is correct.

I have no motivation to add non-standard features.
There are no plans to implement the proposed features.

**Comment by razafinarivohanania** [comment]
Many thanks for your explanation. :)

**Comment by flaviut** [comment]
I think not implementing this is reasonable, but it's interesting that Firefox & Chrome [don't enforce secure on localhost](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#secure). This isn't part of the spec, but it's extremely convenient for local testing.

Anyway, here's a workaround:

```

class UnsecureCookieJar extends CookieJar {
    getCookies(currentUrl: string, options?: CookieJar.GetCookiesOptions): Promise<Cookie[]>;
    getCookies(
        currentUrl: string,
        options: CookieJar.GetCookiesOptions,
        cb: (err: Error | null, cookies: Cookie[]) => void,
    ): void;
    getCookies(currentUrl: string, cb: (err: Error | null, cookies: Cookie[]) => void): void;
    getCookies(currentUrl: string, cbOrOptions?: any, cb?: any): any {
        let options;
        if (typeof cbOrOptions === 'function') {
            cb = cbOrOptions;
            options = {};
        } else {
            options = cbOrOptions || {};
        }

        options.secure = true;
        return super.getCookies(currentUrl, options, cb);
    }
}
```
