### ISSUE TITLE
@types/tough-cookie ^2.3.3 to ^4.0.0 release

### ISSUE THREAD

**Issue by bmiddha** [3846masa/axios-cookiejar-support#277]
be87d1e387e220eae1e9fd70f020ee694ada620f updates @types/tough-cookie from ^2.3.3 to ^4.0.0. This change isn't in the latest npm release of this package yet.
Consuming the package with the stale dependency can result in the following TypeScript error:
```
error TS2322: Type 'CookieJar' is not assignable to type 'boolean | CookieJar'.
  Type 'import("node_modules/@types/tough-cookie/index").CookieJar' is not assignable to type 'import("node_modules/axios-cookiejar-support/node_modules/@types/tough-cookie/index").CookieJar'.
```
The fix in the mean time is to downgrade @types/tough-cookie to ^2.3.3 in the project consuming `axios-cookiejar-support` or manually updating the npm shrinkwrap for the package.

Releasing a new version based on the current master branch should resolve the issue.

Thanks for writing this package. :tada:

**Comment by 3846masa** [comment]
I decide to remove tough-cookie from dependencies and add them to peerDependencies.
This issue will be resolved with that fixes.
v1.0.0 included fixes was released, please try it.

NOTE:
If you didn't install tough-cookie directly in your project, please install manually.
```sh
npm i tough-cookie @types/tough-cookie
```

**Comment by bmiddha** [comment]
The new release fixes the issue. 
![](https://media.giphy.com/media/maNB0qAiRVAty/giphy.gif)
