### ISSUE TITLE
Request failed with status code 301

### ISSUE THREAD

**Issue by terion-name** [3846masa/axios-cookiejar-support#279]
Adding `axiosCookieJarSupport` leads to redirects fail (for example on https://google.com/).

With simple code:

```js
const axios = require('axios');
const axiosCookieJarSupport = require('axios-cookiejar-support').default;
const tough = require('tough-cookie');
const HttpsProxyAgent = require('https-proxy-agent');
const HttpProxyAgent = require('http-proxy-agent');

axiosCookieJarSupport(axios);

async function(page, proxy) {
    const cookieJar = new tough.CookieJar();

    const httpsAgent = new HttpsProxyAgent(httpsAgentConfig);
    const httpAgent = new HttpProxyAgent(httpAgentConfig);

    page.on("request", async (req) => {
    const resp = await axios({
          url: req.url(),
          method: req.method(),
          headers,
          data: req.postData(),
          timeout: 30000,
          responseType: 'stream',
          proxy: false,
          httpsAgent,
          httpAgent,
          jar: cookieJar,
          withCredentials: true,
        });
    //...
    }
}
```
REQUEST ERROR https://google.com/ Request failed with status code 301

adding/removing httpAgent and httpsAgent doesn't change anything.  without `axiosCookieJarSupport` everything works fine

**Comment by 3846masa** [comment]
I'll tried but it works fine.
https://runkit.com/3846masa/5e927fb4d15ea1001ac507c5

Please tell me the specific value of your request.

**Comment by terion-name** [comment]
@3846masa I've figured out: adding "host" header leads to  this.
```
const resp = await axios({
          url: req.url(),
          method: req.method(),
          headers: {
            ...req.headers(),
            "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
            "accept-encoding": "gzip, deflate",
            'Accept-Language': 'en-US,en;q=0.9', 
           "host": new URL(req.url()).hostname,  // this one
            "connection": "keep-alive",
            ...(req.isNavigationRequest() ? {
              "sec-fetch-mode": "navigate",
              "sec-fetch-site": "none",
              "sec-fetch-user": "?1"
            } : {
              "sec-fetch-mode": "no-cors",
              "sec-fetch-site": "same-origin"
            })
          },
```

**Comment by 3846masa** [comment]
The original axios use https://github.com/follow-redirects/follow-redirects for redirects.
`follow-redirects` rewrites `Host` header when redirecting.

However, axios-cookiejar-support cannot use `follow-redirects` because cookies in all response should be parsed.

BTW, `Host` header is not necessary to set to axios, it set by Node.js `http` / `https` module  automatically.

> setHost <boolean>: Specifies whether or not to automatically add the Host header. Defaults to true.
Source: https://nodejs.org/api/http.html#http_http_request_options_callback

**Comment by terion-name** [comment]
@3846masa so the solution is just not to set host header? ok, thank you. will close for now and investigatte further
