### ISSUE TITLE
any way to use it on the react native

### ISSUE THREAD

**Issue by SuThaw** [3846masa/axios-cookiejar-support#302]
I am trying to use this library on react native. But the library is using this function
function noopEnableCookieJarSupport (instance) {
return instance;
}. 
So, is there anyway to use it on react-native ?

**Comment by 3846masa** [comment]
This library does not support React Native and does not plan to support it in the future.

**Comment by pe-johndpope** [comment]
this gets the cookie working with 
https://github.com/salesforce/tough-cookie/pull/227
