### ISSUE TITLE
set-cookie notwork by axios({ method: 'xxx' })

### ISSUE THREAD

**Issue by Louis0723** [3846masa/axios-cookiejar-support#321]
set-cookie not work by axios({ method: 'xxx',... })

only axios.xxx(...)

**Comment by Lursun** [comment]
your overwriteRequestFunction  invalid  when use axios(...)

**Comment by 3846masa** [comment]
Sorry for the delay in response.
This issue has been resolved with the release of v2.0.0.

If you think this issue is still unresolved, please reopen it.
