### ISSUE TITLE
Get / Set Store

### ISSUE THREAD

**Issue by cnikolov** [3846masa/axios-cookiejar-support#322]
Hi I was wondering if there is a way I could , use a store, save it in db and reuse it later?

Something like
First Request
axiosCookieSuport(axios);
const cookieJar = new tough.CookieJar();
let apiCookie = { withCredentials: true, jar: cookieJar };
saveToDb(apiCookie);
Second Request
let storedSession = myDb.getSession(); //This is apiCookie
apiCookie = storedSession.

I have the infrastructure for db etc. I just need to know how to set / get store from cookiejar.

**Comment by 3846masa** [comment]
> I just need to know how to set / get store from cookiejar.

That's the role of a tough-cookie.
Please read [salesforce/tough-cookie](https://github.com/salesforce/tough-cookie) document.
