### ISSUE TITLE
baseURL causes cookie not in host's domain

### ISSUE THREAD

**Issue by ha6000** [3846masa/axios-cookiejar-support#332]
The `config.url` passed to `CookieJar` does not include the baseURL and causes `tough-cookie` not knowing what the domain is and causing error. I would suggest combining the baseURL and the `config.url` or getting the url from somewhere else.

**Comment by ha6000** [comment]
Pull request #333 realized it might be a duplicate of #320

**Comment by 3846masa** [comment]
Sorry for the delay in response.
This issue has been resolved with the release of v2.0.0.

If you think this issue is still unresolved, please reopen it.
