### ISSUE TITLE
maxRedirects set to 0 and 3xx throw errors

### ISSUE THREAD

**Issue by IshFx** [3846masa/axios-cookiejar-support#341]
Hello,

I'm just following up on #161.

As said in the last comment, validateStatus is removed and never restored.
Also, maxRedirects is set to 0.

When i use the `axios-retry` plugin, 3xx statuses throw an error.
This happens because `axios-cookiejar-support` mutates the request config (sets maxRedirects to 0). This config is passed to the retried request which throws an error if the response status is 3xx.

Whats the reason behind :
```js
Object.assign(config, {
    maxRedirects: 0,
});
delete config.validateStatus;
```

Thanks in advance.

**Comment by 3846masa** [comment]
Sorry for the delay in response.
This issue has been resolved with the release of v2.0.0.

If you think this issue is still unresolved, please reopen it.
