### ISSUE TITLE
axios-cookiejar-support redirect method not consistent with axios redirect method

### ISSUE THREAD

**Issue by aevans04** [3846masa/axios-cookiejar-support#380]
When submitting request via axios to a url that returns redirect status codes 301, 302, 303, 307 or 308, axios will call the redirected location using the original method eg. HEAD, GET, POST, etc. When submitting request using axios with axios-cookiejar-support, the method to the redirected location is set to GET except for 307 status. This is partially consistent with browser behavior explained below except 308 status should also retain original method on redirect:

https://stackoverflow.com/questions/2068418/whats-the-difference-between-a-302-and-a-307-redirect#:~:text=302%20is%20temporary%20redirect%2C%20which,response%20generated%20by%20the%20browser. 

I think the code handling this is in node_modules\axios-cookiejar-support\lib\interceptors\response.js on line 59:

  if (local.redirectCount >= 0 && (0, _isRedirect.default)(statusCode) && !!headers['location']) {
    if (response.status !== 307) {
      config.method = 'get';
    }

**Question: Should axios-cookiejar-support handle redirect responses the same way that axios handles redirect responses?**

Here is code based on axios unit test (https://github.com/axios/axios/pull/1758/commits) I used to test with and without coookie jar support for different redirect codes:

const axios = require('axios').default;

const useCookieJar = true;
const redirectStatus = 308;

if (useCookieJar) {
	const axiosCookieJarSupport = require('axios-cookiejar-support').default;
	axiosCookieJarSupport(axios);
}

//testing axios redirect
const http = require('http');
const urllib = require('url');
let server = http.createServer(function (req, res) {
	if (req.method.toLowerCase() !== "head") {
		res.statusCode = 400;
		res.end();
		return;
	}

	let parsed = urllib.parse(req.url);
	if (parsed.pathname === '/one') {
		res.setHeader('Location', '/two');
		res.statusCode = redirectStatus;
		res.end();
	} else {
		res.end();
	}
}).listen(4444, function () {
	axios('http://localhost:4444/one',{method:'head'})
	.then(function (res) {
		console.log(res.status);
	}).catch(function (err) {
		console.error(err);
		console.error('redirected request does not maintain original method');
	});
});

console.log(response);

**Comment by 3846masa** [comment]
Sorry for the delay in response.
This issue has been resolved with the release of v2.0.0.

If you think this issue is still unresolved, please reopen it.
