### ISSUE TITLE
Error: Cannot read property 'set-cookie' of undefined

### ISSUE THREAD

**Issue by arrondev** [3846masa/axios-cookiejar-support#399]
If axios-cookiejar-support is used and the API service is down, an error occurs during the interceptor from this library, masking the real error.

For example, the response contains the following `message:'connect ECONNREFUSED XXXXX'`

The response interceptor will try to access response.headers['set-cookie'] but headers is undefined since it failed to connect.  We need an additional check to ensure the headers is valid before trying to access 'set-cookie'.

![image](https://user-images.githubusercontent.com/610140/129596703-0a74ed96-6684-405f-8ea7-04ae540d4b04.png)

**Comment by 3846masa** [comment]
Sorry for the delay in response.
This issue has been resolved with the release of v2.0.0.

If you think this issue is still unresolved, please reopen it.
