### ISSUE TITLE
After moving to latest release, I am getting an error: The "url" argument must be of type string

### ISSUE THREAD

**Issue by arrondev** [3846masa/axios-cookiejar-support#413]
code:'ERR_INVALID_ARG_TYPE'
message:'The "url" argument must be of type string. Received undefined'
stack:'TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined

I went from v1.01 to latest 2.0.1 version and did all the work outlined in the migration doc.

```js
import { wrapper } from 'axios-cookiejar-support';
import { CookieJar } from 'tough-cookie';

const request = axios.create({
  jar: new CookieJar()
  }):
  wrapper(request);

const url = 'https://actualUrl';
request.post(url, {data: abc});
```
    
If I move back to v1.0.1 and change the import back, it works fine.  The rest of the code is the same.

**Comment by 3846masa** [comment]
It looks like it works fine.
Runkit: https://runkit.com/3846masa/61560b22049fac00096156b2

I would like to know which function is causing the error.
Please share a detailed error stack trace.
