### ISSUE TITLE
POST with Body Not Passing Cookies

### ISSUE THREAD

**Issue by consultwithmike** [3846masa/axios-cookiejar-support#42]
I have a POST that contains a body, and for some reason, the Cookies aren't getting injected into the request. What did I do wrong here:

    return axios
        .post(
            urlJoin(
                config.portal.url,
                'Account/Register'),
            {
                UserName: "testing_engine@test.com",
                UserFirstName: "First Name",
                UserLastName: "Last Name",
                Email: "testing_engine@test.com",
                Password: "...",
                ConfirmPassword: "..."
            },
            {
                jar: cookieJar,
                withCredentials: true
            })
        .then(res => callback())
        .catch(err => callback(err))

The weird part is, if I perform a GET against the same endpoint the Cookies get passed:

    return axios
        .get(
            urlJoin(
                config.portal.url,
                'Account/Register'),
            {
                jar: cookieJar,
                withCredentials: true
            })
        .then(res => callback())
        .catch(err => callback(err));

Also, if I perform a POST without a body, they get passed:

    .post(
        urlJoin(
            config.portal.url,
            `Account/LoginApi?UserName=${config.portal.userName}&Password=${config.portal.password}`),
        null,
        {
            jar: cookieJar,
            withCredentials: true
        })
    .then(res => callback())
    .catch(err => callback(err))

**Comment by consultwithmike** [comment]
I've also created an Stackoverflow post, and created a new tag for `axios-cookiejar-support` here: http://stackoverflow.com/questions/41142299/post-with-body-not-passing-cookies

**Comment by 3846masa** [comment]
I tried POST with body and cookies.
https://gist.github.com/3846masa/bac9823426239df2b39f508d2f2a64bd

axios passed cookies to server, and axios recieved cookies from server.
It looks fine, so I have no idea to resolve your problem, sorry.

If you think this library causes problem, please re-send issue with more details.

**Comment by Billy-** [comment]
I am trying to post to Github API as part of the oAuth flow, and the response I am getting is "Cookies must be enabled to use GitHub.".

Any help on this would be much appreciated because I can't think of any reason why this is and I have set up axios-cookiejar-support as per spec.

**Comment by Billy-** [comment]
```
const axios = require('axios')
const axiosCookieJarSupport = require('@3846masa/axios-cookiejar-support')
const tough = require('tough-cookie')
//...
axiosCookieJarSupport(axios)
const cookieJar = new tough.CookieJar()
//...
axios.post('https://github.com/login.oauth/access_token',
    qs.stringify({
        client_id: GH_CLIENT_ID,
        client_secret: GH_CLIENT_SECRET,
        code: code
    }),
    {
        jar: cookieJar,
        withCredentials: true,
    }
)
.then(oAuthRes => {
    res.end('cool 8-) ')
})
.catch(e => {
    res.end('not cool. :( ' + (e.response && e.response.data ? e.response.data : e.message))
})
```

The response data I get from Github is "Cookies must be enabled to use GitHub.". I'm not sure what the problem is.

**Comment by 3846masa** [comment]
First, Your API URL is invalid.
API URL is `https://github.com/login/oauth/access_token`.
See https://developer.github.com/v3/oauth/#web-application-flow .

When fix URL, that code worked fine.

And, cookies is not required using this API.
So, you don't need @3846masa/axios-cookiejar-support .

**Comment by Billy-** [comment]
Wow. So sorry for wasting your time! \*facepalm\*. Feel free to delete my comments.
