### ISSUE TITLE
Error: in dependency http-cookie-agent@^3

### ISSUE THREAD

**Issue by jvddavid** [3846masa/axios-cookiejar-support#484]
## Describe the bug

On import axios-cookiejar-support throw error no such file or directory on import http-cookie-agent

![error-http-cookie](https://user-images.githubusercontent.com/46910583/167266850-412d6e0b-b780-4dc5-a7d3-efe76424c90b.png)

## To Reproduce

1. install axios-cookiejar-support@^4
2. export { wrapper } from 'axios-cookiejar-support'
3. create a AxiosIntance with wrapper

## Environments

- OS: Windows 10
- Node.js version: 16.15.0
- axios version: ^0.27.2
- tough-cookie version: ^4.0.0

**Comment by 3846masa** [comment]
Sorry for the inconvenience.
I am now fixing it as http-cookie-agent@4.0.0 and axios-cookiejar-support@3.0.1.

Once they are released, the issues will be closed automatically.
Thanks for your report.

**Comment by jvddavid** [comment]
Thanks
