### ISSUE TITLE
Error: Cannot find module 'node:url'

### ISSUE THREAD

**Issue by felicoz** [3846masa/axios-cookiejar-support#580]
## Describe the bug

I used the exactly the same sample code from github and this error came out. I have tried to use different node version but didn't help at all

Error: Cannot find module 'node:url'
Require stack:
- /Users/felicoz/Workspace/sell/node_modules/http-cookie-agent/dist/http/create_cookie_agent.js
- /Users/felicoz/Workspace/sell/node_modules/http-cookie-agent/dist/http/index.js
- /Users/felicoz/Workspace/sell/node_modules/http-cookie-agent/http/index.js
- /Users/felicoz/Workspace/sell/node_modules/axios-cookiejar-support/dist/index.js
...
..
    at Object.<anonymous> (/Users/felicoz/Workspace/sell/node_modules/http-cookie-agent/dist/http/create_cookie_agent.js:8:39) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/felicoz/Workspace/sell/node_modules/http-cookie-agent/dist/http/create_cookie_agent.js',
    '/Users/felicoz/Workspace/sell/node_modules/http-cookie-agent/dist/http/index.js',
    '/Users/felicoz/Workspace/sell/node_modules/http-cookie-agent/http/index.js',
    '/Users/felicoz/Workspace/sell/node_modules/axios-cookiejar-support/dist/index.js',
..
...
..
  ]
}

## Environments

- OS: apple m1 12.1
- Node.js version: 14.18.0
- axios version: 0.27.2
- tough-cookie version: 4.0.3

**Comment by daiangm** [comment]
@felicoz  You can install the version 2.0.5 to fix it

**Comment by coolbho3k** [comment]
I am getting this issue :( Installing 2.0.5 seems to have fixed.

**Comment by chinhnguyen90** [comment]
I get same error in version 5.0.3. Please help me. Thank you!
