### ISSUE TITLE
Cookie jar is empty after making GET request in React Native

### ISSUE THREAD

**Issue by maximilian** [3846masa/axios-cookiejar-support#636]
Hi,

I've been having issues for a few hours now trying to get this package to work with React Native. The following example code works without errors, it simply does not return any cookies in the cookie jar: https://github.com/3846masa/axios-cookiejar-support/blob/main/examples/basic.cjs

Am I missing something? I did see tough-cookie got a [PR approved](https://github.com/salesforce/tough-cookie/pull/227) for RN compatibility as well.

**Comment by 3846masa** [comment]
axios-cookiejar-support uses httpAgent to read and write cookies.
Since httpAgent exists only in Node.js, it does not work in React Native.

There are no plans to support React Native in the future.
