### ISSUE TITLE
jar not fully working

### ISSUE THREAD

**Issue by edgracilla** [3846masa/axios-cookiejar-support#84]
This jar support for axios is not working with shopping carts that relies on cookies. I switched to 'request' package to proceed with my project.

**Comment by 3846masa** [comment]
Please more details.

- Your code.
- What site you access.
- That site mock (optional)

**Comment by edgracilla** [comment]
here is the gist.
https://gist.github.com/edgracilla/1b690dea778f2fdc383cba322e89b872

Tested url and params using `request` lib with jar and its working.

Or did I miss something?

**Comment by 3846masa** [comment]
When `withCredentials` is false, axios **don't** send cookie (like XHR).

See https://github.com/3846masa/axios-cookiejar-support#extended-request-config.

**Comment by edgracilla** [comment]
Tried to turn it to `true` same thing happen.

**Comment by 3846masa** [comment]
You must `qs.stringify(formData)` when post formData via axios.

See axios Docs (https://github.com/mzabriskie/axios#using-applicationx-www-form-urlencoded-format).

**Comment by edgracilla** [comment]
`const qs = require('qs')
const querystring = require('querystring')`

Tried to stringify using each of the above libs, same result, not working. I already switched to `request` lib but this axios issue should be handled. The gist i provided is ready to execute in node. Please refer on that and test it.

**Comment by 3846masa** [comment]
I did test your code with fixing `querystring` and `withCredentials`, and code works fine.
Please check your code, thx.

**Comment by edgracilla** [comment]
Got it. It is indeed my fault. Apologies if I didn't check the docs first. You may close this issue.

Thanks!
