### ISSUE TITLE
TS2345: Argument of type 'AxiosInstance' is not assignable to parameter of type 'AxiosStatic | AxiosInstance'

### ISSUE THREAD

**Issue by mrjackyliang** [3846masa/axios-cookiejar-support#856]
## Describe the bug

<img width="1155" alt="Screenshot 2023-11-20 at 12 54 22 AM" src="https://github.com/3846masa/axios-cookiejar-support/assets/9779803/ab8fbf2d-6fba-4a6d-aab6-1e7672a9893f">

## To Reproduce

1. Use the example code provided.
2. TypeScript and ESM

## Expected behavior

Expect to work.

## Code that reproduces the bug

I get this error: TS2345: Argument of type 'AxiosInstance' is not assignable to parameter of type 'AxiosStatic | AxiosInstance'

## Environments

- OS: macOS 14.1.1
- Node.js version: 18.18.2
- axios version: 1.6.2
- tough-cookie version: 4.1.3

**Comment by 3846masa** [comment]
Thanks for reporting.
Please fill out `Environments` section for debugging.

**Comment by mrjackyliang** [comment]
> Thanks for reporting. Please fill out `Environments` section for debugging.

Apologize, and just updated. Thanks for the quick reply!

**Comment by mrjackyliang** [comment]
Weird setting, but I was playing around with the `tsconfig.json` settings and changed this. Not sure I completely understand why, but apparently `bundler` is a new thing in TS5+

Old:
```sh
    "module": "ES2022",
    "moduleResolution": "Node16",
```

New:
```sh
    "module": "ES2022",
    "moduleResolution": "bundler",
```

**Comment by mrjackyliang** [comment]
I solved it by switching to NodeNext

**Comment by flleeppyy** [comment]
~~Hiya, I still get this error, switching out keys in my tsconfig did not fix it. Same exact error as listed in the issue.

```
Argument of type 'Promise<AxiosResponse<any, any, {}>>' is not assignable to parameter of type 'AxiosStatic | AxiosInstance'.ts(2345)
```

<img width="773" height="277" alt="Image" src="https://github.com/user-attachments/assets/e9a171b1-3995-4981-9a69-8c83ccf53ab1" />

~~

Solution was to just do axios.create() instead of axios()
