### ISSUE TITLE
Unhelpful Message on TypeError: Cannot read property 'backupOptions' of undefined

### ISSUE THREAD

**Issue by machineghost** [3846masa/axios-cookiejar-support#89]
When you get a `TypeError: Cannot read property 'backupOptions' of undefined` it's because of this code:

    const local = config._COOKIEJAR_SUPPORT_LOCAL;
    local.backupOptions = local.backupOptions || {};

If `config._COOKIEJAR_SUPPORT_LOCAL` is missing then (unsurprisingly) `undefined.backupOptions` will result in an error.

However, when this happens it's obvious that the plug-in isn't being applied, because otherwise `config._COOKIEJAR_SUPPORT_LOCAL` would be present.  However, that fact is not obvious to a new user (I only figured it out by reading the code).

Therefore a more helpful error message would tell the user what they did wrong, or at least give them a general idea.  Something to the effect of "Hey dummy you forgot to include `jar: cookieJar` in your axios config or you forgot to wrap your axios instance with axiosCookieJarSupport" would make this error much less painful to someone trying to use the plugin for the first time.

**Comment by 3846masa** [comment]
First, #87 case is specially case.
axios interceptors allows only `(value: V) => V | Promise<V>` type.
However, #87 passes `(value: V) => Object` to interceptors, so Error was caused.
(See https://github.com/mzabriskie/axios/blob/v0.16.1/index.d.ts#L92-L110)
(NOTE: other plugin will cause Error in this usage, I think)

`TypeError: Cannot read property 'backupOptions' of undefined` cannot show when code is correct usage of original Axios.

I think library **don't need to support** for errors when code is **incorrect usage of original Axios**.

If you have other pattern cause this Error, please show me example code.

**Comment by machineghost** [comment]
So basically, if someone is new to your library and makes a mistake, one which you can very easily identify and provide a helpful message about ... screw them, it's their fault for not knowing your library as well as you do?!?

Mature library maintainers would prefer to let users, ESPECIALLY new ones, know when they make a mistake.

**Comment by 3846masa** [comment]
I know your opinion.

However, I think it is not necessary.
I don't know the generally case that Error like this was caused.
This library won't cause `_COOKIEJAR_SUPPORT_LOCAL` Error in normaly usage of original axios.
Error that be caused when using incorrectly is very various, I can't support them.

I don't want to support wrong code that be written without reading documents.

If you disagree with my decide, please fork this and create new library.
(Fortunately, this library is MIT License.)
Thanks.
