### ISSUE TITLE
error TS2339: Property 'jar' does not exist on type 'AxiosRequestConfig'.

### ISSUE THREAD

**Issue by bennyn** [3846masa/axios-cookiejar-support#97]
I am using [axios](https://github.com/mzabriskie/axios) with TypeScript (because it has typings) and now I want to apply "axios-cookiejar-support". 

Unfortunately, there are no type definitions for "axios-cookiejar-support", so TypeScript complains because "axios-cookiejar-support" wants to add a property ("jar") to the axios config which is not defined in axio's typings:

>error TS2339: Property 'jar' does not exist on type 'AxiosRequestConfig'.

Source code for axio's typings is:
- https://github.com/mzabriskie/axios/blob/v0.16.2/index.d.ts#L19

Broken code:

```typescript
public sendRequest(config: AxiosRequestConfig): AxiosPromise {
  config.baseURL = this.baseURL;
  config.jar = this.cookieJar;
  return axios.request(config);
}
```

I can only fix it with `any` which will remove the benefits of having types:

```typescript
public sendRequest(config: any): AxiosPromise {
  config.baseURL = this.baseURL;
  config.jar = this.cookieJar;
  return axios.request(config);
}
```

**Comment by 3846masa** [comment]
Thanks for issue. I made definition file.
It will be released as v0.1.0 soon.

**Comment by 3846masa** [comment]
Released.
Please try to reinstall my package.

**Comment by bennyn** [comment]
**Wooow!** That was the fastest turn around ever! 😲

Thank you so much!! 😊

**Comment by damianobarbati** [comment]
@bennycode @3846masa are the typing correct with the last version of `axios-cookiejar-support` and `axios`?

<img width="1200" alt="Screenshot 2023-01-23 at 21 28 20" src="https://user-images.githubusercontent.com/2225869/214143032-8afcc089-4fab-4bee-b668-b9521648ba6d.png">
